#This file is used to build external dependencies using ExternalProject
include(ExternalProject)

message(${CMAKE_BINARY_DIR})
set(INSTALL_PATH ${CMAKE_BINARY_DIR}/thirdparty)
set(THIRDPARTY_DIR ${CMAKE_SOURCE_DIR}/thirdparty)
message(${THIRDPARTY_DIR})

ExternalProject_Add(RF24
	SOURCE_DIR ${THIRDPARTY_DIR}/RF24
	BUILD_IN_SOURCE 1
	INSTALL_DIR ${INSTALL_PATH}
	STAMP_DIR ${INSTALL_PATH}/Stamp
	TMP_DIR ${INSTALL_PATH}/tmp
	DOWNLOAD_DIR ${INSTALL_PATH}
	CONFIGURE_COMMAND ./configure --driver=SPIDEV --prefix=${INSTALL_PATH}
	BUILD_COMMAND make
	INSTALL_COMMAND make install
	)

ExternalProject_Add(wiringPi
	SOURCE_DIR ${THIRDPARTY_DIR}/wiringPi/wiringPi
	BUILD_IN_SOURCE 1
	INSTALL_DIR ${INSTALL_PATH}
	STAMP_DIR ${INSTALL_PATH}/Stamp
	TMP_DIR ${INSTALL_PATH}/tmp
	DOWNLOAD_DIR ${INSTALL_PATH}
	CONFIGURE_COMMAND ""
	BUILD_COMMAND make
	INSTALL_COMMAND make install DESTDIR=${INSTALL_PATH} PREFIX=""
	)

ExternalProject_Add(wiringPiDev
	DEPENDS wiringPi
	SOURCE_DIR ${THIRDPARTY_DIR}/wiringPi/devLib
	BUILD_IN_SOURCE 1
	INSTALL_DIR ${INSTALL_PATH}
	STAMP_DIR ${INSTALL_PATH}/Stamp
	TMP_DIR ${INSTALL_PATH}/tmp
	DOWNLOAD_DIR ${INSTALL_PATH}
	CONFIGURE_COMMAND ""
	BUILD_COMMAND make
	INSTALL_COMMAND make install DESTDIR=${INSTALL_PATH} PREFIX=""
	)

ExternalProject_Add(tsl2561
	SOURCE_DIR ${THIRDPARTY_DIR}/tsl2561
	BUILD_IN_SOURCE 1
	INSTALL_DIR ${INSTALL_PATH}
	STAMP_DIR ${INSTALL_PATH}
	TMP_DIR ${INSTALL_PATH}/tmp
	DOWNLOAD_DIR ${INSTALL_PATH}
	CONFIGURE_COMMAND ""
	BUILD_COMMAND make
	INSTALL_COMMAND ${CMAKE_COMMAND} -E copy_if_different ${THRIDPARTY_DIR}/tsl2561/src/tsl2561.h ${INSTALL_DIR}/include/tsl2561.h
					COMMAND ${CMAKE_COMMAND} _E copy_if_different ${THIRDPARTY_DIR}/tsl2561/src/tsl2561.o ${INSTALL_DIR}/lib/tsl2561.o
	)

#Gather variables for using ExternalProjects in build
set(RF24_include ${INSTALL_DIR}/include/RF24)
set(RF24_lib ${INSTALL_PATH}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}rf24${CMAKE_SHARED_LIBRARY_SUFFIX})

set(wiringPi_include ${INSTALL_DIR}/include/)
set(wiringPi_lib ${INSTALL_PATH}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}wiringPi${CMAKE_SHARED_LIBRARY_SUFFIX})

set(wiringPiDev_include ${INSTALL_DIR}/include/)
set(wiringPiDev_lib ${INSTALL_PATH}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}wiringPiDev${CMAKE_SHARED_LIBRARY_SUFFIX})

#set install rules
install(FILES ${RF24_lib} DESTINATION lib COMPONENT Networking)
install(FILES ${wiringPi_lib} ${wiringPiDev_lib} DESTINATION lib COMPONENT SensorPi)