CXXFLAGS = -std=c++1z -pthread -g
CURL = -lcurl
NCURSES = -lncurses
NETWORKING = -lsensorsystem-networking -lrf24
FILESYSTEM = -lstdc++fs
REPO = ..
RF24_INCLUDE = $(REPO)/thirdparty
RF24_DIR = $(REPO)/thirdparty/RF24
NETWORKING_INCLUDE = $(REPO)/Networking/include
NETWORKING_DIR = $(REPO)/Networking

INCLUDES = -I./include -I$(RF24_INCLUDE) -I$(NETWORKING_INCLUDE)
LIBS =  $(NETWORKING_DIR)/libsensorsystem-networking.so
OBJECTS = dropboxstorage.o csvfilestorage.o wifiinternetdevice.o helperfunctions.o cursesui.o config.o measurement.o

OBJ_COMMAND = $(CXX) $(CXXFLAGS) $(INCLUDES) -c $<

ifneq ($(words $(MAKECMDGOALS)),1)
.DEFAULT_GOAL = all
%:
        @$(MAKE) $@ --no-print-directory -rRf $(firstword $(MAKEFILE_LIST))
else
ifndef ECHO
T := $(shell $(MAKE) $(MAKECMDGOALS) --no-print-directory \
      -nrRf $(firstword $(MAKEFILE_LIST)) \
      ECHO="COUNTTHIS" | grep -c "COUNTTHIS")
endif

N := x
C = $(words $N)$(eval N := x $N)
ECHO = echo "`expr " [\`expr $C '*' 100 / $T\`" : '.*\(....\)$$'`%]"
endif

.PHONY: all install

all: sensorsystem-hub
	@$(ECHO) Build complete

install: all
	@$(ECHO) Installing program to /usr/local/bin
	@install -m 0755 ./sensorsystem-hub /usr/local/bin/

sensorsystem-hub: $(OBJECTS) ./src/main.cpp $(LIBS)
	@$(ECHO) Linking and building program
	@$(CXX) $(CXXFLAGS) $(INCLUDES) -o $@ $(OBJECTS) ./src/main.cpp $(LIBS) $(FILESYSTEM) $(NETWORKING) $(NCURSES) $(CURL)

dropboxstorage.o: ./src/storage/dropboxstorage.cpp ./include/hub/storage/dropboxstorage.h ./include/hub/storage/remotestorage.h
	@$(ECHO) Builing dropboxstorage.o
	@$(OBJ_COMMAND)

csvfilestorage.o: ./src/storage/csvfilestorage.cpp ./include/hub/storage/csvfilestorage.h ./include/hub/storage/filestorage.h
	@$(ECHO) Builing csvfilestorage.o
	@$(OBJ_COMMAND)
	
wifiinternetdevice.o: ./src/internet/wifiinternetdevice.cpp ./include/hub/internet/wifiinternetdevice.h ./include/hub/internet/wifiinternetdevice.h
	@$(ECHO) Builing wifiinternetdevice.o
	@$(OBJ_COMMAND)
	
helperfunctions.o: ./src/internet/helperfunctions.cpp ./include/hub/internet/helperfunctions.h
	@$(ECHO) Builing helperfunctions.o
	@$(OBJ_COMMAND)

cursesui.o: ./src/cursesui.cpp ./include/hub/cursesui.h
	@$(ECHO) Builing cursesui.o
	@$(OBJ_COMMAND)
	
config.o: ./src/config.cpp ./include/hub/config.h Networking
	@$(ECHO) Builing config.o
	@$(OBJ_COMMAND)
	
measurement.o: ./src/measurement.cpp ./include/hub/measurement.h
	@$(ECHO) Builing measurement.o
	@$(OBJ_COMMAND)

	